// Autogenerated/Strict Spec Bindings from openapi.yaml
export interface Todo {
  id: string;
  title: string;
  description?: string;
  completed: boolean;
  createdAt?: string;
}

export interface TodoInput {
  title: string;
  description?: string;
}

const rawApiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000';
// Sanitizamos para que nunca haya doble slash en la ruta que pueda causar un 404 en Azure
const API_URL = rawApiUrl.replace(/\/$/, "");

export async function getTodos(): Promise<Todo[]> {
  const res = await fetch(`${API_URL}/todos`);
  if (!res.ok) throw new Error('Failed to fetch todos');
  return res.json();
}

export async function createTodo(todo: TodoInput): Promise<Todo> {
  const res = await fetch(`${API_URL}/todos`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(todo),
  });
  if (!res.ok) throw new Error('Failed to create todo');
  return res.json();
}

export async function updateTodo(id: string, completed: boolean): Promise<void> {
  const res = await fetch(`${API_URL}/todos/${id}`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ completed }),
  });
  if (!res.ok) throw new Error('Failed to update todo');
}

export async function deleteTodo(id: string): Promise<void> {
  const res = await fetch(`${API_URL}/todos/${id}`, {
    method: 'DELETE',
  });
  if (!res.ok) throw new Error('Failed to delete todo');
}
